services:
  scheduler:
    image: mailingscheduler.console
    build:
      context: .
      dockerfile: src/MailingScheduler.Console/Dockerfile
    environment:
      CONNECTION_STRING: 'Host=postgres;Port=5432;Database=postgres;User Id=postgres;Password=postgres'
      MAX_TO_FETCH: '500000'
      MAX_SEND_SPEED: '10000'
      WORK_INTERVAL: '1'
      UNIFORM_FRACTION: '0.03'
      PRIORITY_FRACTION: '0.05'
      NON_PRIORITY_FRACTION: '0.01'
    
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
        
volumes: 
  postgres-volume: 
    
  
